package goodorbad.goodorbad.exception;

public class IdNotFoundException extends RuntimeException{ //상속 받아서 내부를 정의하지 않아도 됨
}
